// @ts-check
/** @type {import('@stryker-mutator/api/core').PartialStrykerOptions} */
const config = {
	packageManager: "pnpm",
	plugins: ["@stryker-mutator/vitest-runner"],
	reporters: ["html", "clear-text", "progress"],
	htmlReporter: {
		fileName: "reports/mutation/mutation.html",
	},
	testRunner: "vitest",
	vitest: {
		configFile: "vitest.config.ts",
	},
	coverageAnalysis: "perTest",
	mutate: [
		"src/**/*.ts",
		"src/**/*.tsx",
		// Exclude the same files as vitest coverage
		"!**/*.d.ts",
		"!**/*.test.*",
		"!**/*.spec.*",
		"!src/test/**",
		"!src/stories/**",
		"!src/components/ui/**",
		"!src/instrumentation*.ts",
		"!src/components/clients/*View.tsx",
		"!src/components/transactions/*View.tsx",
		"!src/hooks/use-mobile.ts",
		"!src/types/catalog.ts",
		"!src/types/transaction.ts",
		"!src/types/client-address.ts",
		"!src/types/client-document.ts",
		"!src/app/**",
		"!src/middleware.ts",
		"!src/lib/auth/**",
		"!src/components/settings/**",
		"!src/components/layout/DashboardLayout.tsx",
		"!src/components/layout/Logo.tsx",
		"!src/components/layout/DashboardFullscreen.tsx",
		"!src/hooks/useSidebarSettings.ts",
		"!src/components/clients/ClientsPageContent.tsx",
		"!src/algtools/ui.tsx",
		"!src/hooks/useViewportHeight.ts",
		"!src/hooks/useJwt.ts",
		"!src/hooks/useUrlFilters.ts",
		"!src/hooks/useDataTableUrlFilters.ts",
		"!src/hooks/useOrgNavigation.ts",
		"!src/lib/navigation.ts",
		"!src/lib/testHelpers.ts",
		"!src/components/**/index.ts",
		"!src/components/data-table/types.ts",
		"!src/lib/api/imports.ts",
		"!src/hooks/useImportSSE.ts",
		"!src/components/import/**",
		"!src/types/import.ts",
		"!src/components/chat/**",
		"!src/lib/ai/providers.ts",
		"!src/lib/ai/tools/**",
		"!src/lib/api/file-upload.ts",
		"!src/lib/api/ubos.ts",
		"!src/hooks/useOrgSlug.ts",
		"!src/hooks/useZipCodeLookup.ts",
		"!src/lib/kyc-status.ts",
		"!src/lib/settings/settingsServer.ts",
		"!src/components/subscription/NoAMLAccess.tsx",
		"!src/lib/canvas-shim.ts",
		"!src/lib/document-scanner/**",
		"!src/types/ubo.ts",
		"!src/lib/ai/billing.ts",
		"!src/lib/settings/settingsClient.ts",
		"!src/lib/subscription/subscriptionClient.ts",
		"!src/components/clients/DocumentUploadSection.tsx",
		"!src/components/clients/EditDocumentsSection.tsx",
		"!src/components/clients/LegalRepresentativeForm.tsx",
		"!src/components/clients/UBOSection.tsx",
		"!src/components/clients/ZipCodeAddressFields.tsx",
		"!src/components/clients/KYCProgressIndicator.tsx",
		"!src/components/clients/wizard/**",
		"!src/components/document-scanner/**",
		"!src/components/alerts/CreateManualAlertView.tsx",
	],
	thresholds: {
		high: 80,
		low: 60,
		break: 50,
	},
	timeoutMS: 60000,
	concurrency: 4,
};
export default config;
